# Netlify 배포를 위한 설정 파일
[build]
  publish = "."
  command = "echo 'Static site build'"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.herokuapp.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
